---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/8/8 11:19
---
print("hello world!")

--[[
 多行注释
 斐波那契数列
--]]
function factorial1(n)
    if n == 0 then
        return 1
    else
        return n * factorial1(n - 1)
    end
end
print("factorial1(5)=" .. factorial1(5))
factorial2 = factorial1
print("factorial2(5)=" .. factorial2(5))

print("--------------------------------------")
-- function_test2.lua 脚本文件
function testFun(tab, fun)
    for k, v in pairs(tab) do
        print(fun(k, v));
    end
end

tab = { key1 = "val1", key2 = "val2" };
testFun(tab,
        function(key, val)
            --匿名函数
            return key .. "=" .. val;
        end
);